### PR TITLE
shape check for mask and subjects in distribute method

### PR DESCRIPTION
**Pull request by YSanchezAraujo**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
Can one of the admins verify this patch?

**Comment by buildbot-princeton** [comment]
Can one of the admins verify this patch?

**Comment by mihaic** [comment]
Jenkins, OK to test.

**Comment by mihaic** [comment]
@YSanchezAraujo, as you can see from the CI logs, there are some tests we run to make sure the code is consistent. You should run the same tests yourself before pushing commits by running the `pr-check.sh` script. See more details in the developer documentation:
https://github.com/IntelPNI/brainiak/blob/master/CONTRIBUTING.rst

Please ask if you need any clarification.

**Comment by mihaic** [comment]
Also, please raise `ValueError`s instead of using assertions.

**Comment by mihaic** [comment]
Superseded by #235.

**Pull request closed without merging**
