### PR TITLE
fixing scan_onsets issue in brsa

### PR DESCRIPTION
**Pull request by lcnature**
Make sure that run_TRs calculated from scan_onsets is integer. And make scan_onsets integers in the example.

### CODE REVIEW

**Comment by lcnature** [comment]
@mihaic Hi, can you approve this minor change? Thanks!

**Comment by mihaic** [comment]
@lcnature You have a conflict with the master branch. You can either fix the conflict yourself or accept the PR I made for your branch.

**Comment by lcnature** [comment]
@I accepted it.

**Comment by lcnature** [comment]
@mihaic I accepted it.

**Pull request merged**
