### PR TITLE
Add tda

### PR DESCRIPTION
**Pull request by CameronTEllis**

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
Can one of the admins verify this patch?

**Comment by buildbot-princeton** [comment]
Can one of the admins verify this patch?

**Comment by mihaic** [comment]
Add to whitelist.

**Comment by mihaic** [comment]
We will incorporate this code in the new not-yet-public GPLv3+ repository, https://github.com/IntelPNI/brainiak-extras.

**Comment by xoltar** [comment]
Hi @CameronTEllis I'll add the TDA code Mike and I wrote, plus the PHAT dependencies to https://github.com/IntelPNI/brainiak-extras later this month, after which please resubmit this to that repo. Closing for now.

**Pull request closed without merging**
