### PR TITLE
get_weights should take in data and factors, not the coordinate matrix

### PR DESCRIPTION
**Pull request by mshvartsman**
Looks like a typo, W_ has the wrong thing in it as a result.

### CODE REVIEW

**Comment by buildbot-princeton** [comment]
Can one of the admins verify this patch?

**Comment by buildbot-princeton** [comment]
Can one of the admins verify this patch?

**Comment by xiazhu** [comment]
Yes, please merge this PR.

**Comment by mihaic** [comment]
OK to test.

**Pull request merged**
